// templates/svelte/src/components/QuerySample.svelte
<script lang="ts">
  import { Coins } from '@terra-rebels/terra.js';
  import { ConnectedWallet, createLCDClient } from '@terra-rebels/wallet-controller';
  import { getController } from 'controller';
  import { Subscription } from 'rxjs';
  import { onDestroy, onMount } from 'svelte';
  
  const controller = getController()
  
  let connectedWallet: ConnectedWallet | undefined = undefined;
  let balance: Coins | null = null;
  
  let subscription: Subscription | null = null;
  
  onMount(() => {
    subscription = controller.connectedWallet().subscribe((_connectedWallet) => {
      connectedWallet = _connectedWallet;
      
      if (_connectedWallet) {
        const lcd = createLCDClient({network: _connectedWallet.network});
  
        lcd.bank.balance(_connectedWallet.terraAddress).then(([coins]) => {
          balance = coins;
        });
      } else {
        balance = null;
      }
    });
  });
  
  onDestroy(() => {
    subscription?.unsubscribe();
    connectedWallet = undefined;
  });
</script>

<h1>
  Query Sample
</h1>

{#if !connectedWallet}
  <p>Wallet not connected!</p>
{:else if !!balance}
  <pre>{balance.toString()}</pre>
{/if}

// templates/vue/src/components/QuerySample.vue
<script setup lang="ts">
import { Coins } from '@terra-rebels/terra.js';
import {
  ConnectedWallet,
  createLCDClient,
} from '@terra-rebels/wallet-controller';
import { getController } from 'controller';
import { Subscription } from 'rxjs';
import { onMounted, onUnmounted, ref } from 'vue';

const controller = getController();

const connectedWallet = ref<ConnectedWallet | undefined>(undefined);
const balance = ref<Coins | null>(null);

let subscription: Subscription | null = null;

onMounted(() => {
  subscription = controller.connectedWallet().subscribe((_connectedWallet) => {
    connectedWallet.value = _connectedWallet;

    if (_connectedWallet) {
      const lcd = createLCDClient({ network: _connectedWallet.network });

      lcd.bank.balance(_connectedWallet.terraAddress).then(([coins]) => {
        balance.value = coins;
      });
    } else {
      balance.value = null;
    }
  });
});

onUnmounted(() => {
  subscription?.unsubscribe();
  connectedWallet.value = undefined;
});
</script>

<template>
  <h1>Query Sample</h1>
  <p v-if="!connectedWallet">Wallet not connected!</p>
  <pre v-else-if="!!balance">{{ balance.toString() }}</pre>
</template>
